### ISSUE TITLE
distinguish the weekend days

### ISSUE THREAD

**Issue by gtrullem** [pderksen/WP-Google-Calendar-Events#45]
I'm using your plugin for me wordpress blog but for my needs I had to identifiate with color the saturday and the sunday. I didn't find the option so I have modifiated the php code of 'php-calendar.php' file.

Here is my modification, at line 102 and 103 :

```php
 }else{
      $css_class = ( $timestamp < $time_now ) ? 'gce-day-past' : 'gce-day-future';
      $css_class .= ( $weekday == 5 ) ? ' saturday' : '';
      $css_class .= ( $weekday == 6 ) ? ' sunday' : '';
      $calendar .= '' . esc_html( $day ) . '';
 }
```

Like this, I can define a 'background-color' in my custom CSS file to immediately identifiate the saturday and sunday.

May be it can help someone else or give you an idea to improve your plugin (or, may be, you gonna explain me how to use your plugin to identifiate some specific day without modification).

Thanks a lot for your work ! Great job !!! Thanks you !

P.S. : in 'php-calendar.php', it seems to me that the lines 55 & 57 are identically the same. Idem for the lines 61 & 63... If it's true, I didn't understand why use it in the 'if' AND the 'else' scope.

P.P.S. : sorry for my bad English.

**Comment by nekojira** [comment]
Hi @gtrullem, I have just made a commit in `dev` branch of the plugin - I think this can go in the next version of the plugin

Instead of using 'saturday' or 'sunday', though, I added a class `gce-week-day-<number>` where `<number>` is the number of the day. The array currently begins from 0 which is funny, In future I think I would like to have a human readable count from 1 to 7. But then again, there's to consider that some people begin their week on Sunday other on Mondays. So weekends are not the same for every culture.

So I think in the future I might choose not to maintain these classes; but rather, offer a filter hook so you can add your own or replace them, in accordance with your theme (probably I will pass the classes in an array along with other information, like the weekday number...). 

I know the `php-calendar.php` has parts that don't make much sense, it was inherited from a old plugin and a lot has been built on top of that - but we are refactoring the plugin in order to make it better you can see these changes in `refactor` branch

don't worry about your English, it's not my native language either

**Comment by pderksen** [comment]
Ref to commit: https://github.com/pderksen/WP-Google-Calendar-Events/commit/f4ff7fcd80b77da80965857ec4efd05f8a2aa306

**Comment by gtrullem** [comment]
Thanks @nekojira,

You said :" In future I think I would like to have a human readable count from 1 to 7". Here is my humble contribution (without consideration of culture) : 

`
$css_class .= ' gce-week-day-' . strval( $weekday+1 ) . ' ';
`

Thank you !
